owner: jayTapps
repo: dwp-status

sites:
  - name: Dog Walker Pro API
    url: https://dogwalkerpro.jtapps.co.uk/version.json

assignees:
  - jayTapps

status-website:
  cname: status.jtapps.co.uk
  name: Dog Walker Pro Status
