owner: jaythrussell  # your GitHub username
repo: dwp-status

sites:
  - name: Dog Walker Pro API
    url: https://dogwalkerpro.jtapps.co.uk/version.json

assignees:
  - jaythrussell

status-website:
  cname: status.jtapps.co.uk  # or leave blank if no custom domain
  name: Dog Walker Pro Status

